source 'https://rubygems.org'
group :jekyll_plugins do
    gem 'classifier-reborn', '~> 2.3'
    gem 'jekyll', '~> 4.3'
    gem 'jekyll-archives', '~> 2.2'
    gem 'jekyll-email-protect'
    gem 'jekyll-feed', '~> 0.17'
    gem 'jekyll-get-json'
    gem 'jekyll-imagemagick'
    gem 'jekyll-jupyter-notebook'
    gem 'jekyll-link-attributes'
    gem 'jekyll-minifier', '~> 0.1'
    gem 'jekyll-paginate-v2', '~> 3.0'
    gem 'jekyll-regex-replace'
    gem 'jekyll-scholar', '~> 7.1'
    gem 'jekyll-sitemap', '~> 1.4'
    gem 'jekyll-tabs'
    gem 'jekyll-toc', '~> 0.18'
    gem 'jekyll-twitter-plugin'
    gem 'jemoji'
    gem 'mini_racer'
    gem 'unicode_utils'
    gem 'webrick', '~> 1.8'
end
group :other_plugins do
    gem 'css_parser'
    gem 'feedjira'
    gem 'httparty'
end
